# Generated by Django 4.1.4 on 2022-12-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='Project/%Y/%m/%d')),
                ('picture2', models.ImageField(blank=True, upload_to='Project/%Y/%m/%d')),
                ('picture3', models.ImageField(blank=True, upload_to='Project/%Y/%m/%d')),
                ('picture4', models.ImageField(blank=True, upload_to='Project/%Y/%m/%d')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.picture')),
            ],
        ),
    ]
