# Generated by Django 4.1.4 on 2022-12-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.CreateModel(
            name='DemoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demoImages', models.ImageField(blank=True, upload_to='DemoImages/%Y/%m/%d')),
                ('alt', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
